<HTML>
<HEAD>
<TITLE>Boursorama - Tableaux de cours</TITLE>
<META http-equiv="pragma" content="no-cache">
<META http-equiv="expires" content="Wed, 11 Jul 2001 10:17:07 GMT">
<META Name="description" Content="tous les cours des marchés internationaux de A à Z">
<SCRIPT language="JavaScript" src="/bourso.js"></SCRIPT>
</HEAD>
<BODY BGCOLOR="#FFFFFF" TEXT="#000000" LINK="#003399" VLINK="#003399" ALINK="#FF0000">
<center>
<table border=0 width=760 cellpadding=0 cellspacing=0>
<tr>
<TD valign=top bgcolor="#EEEEEE">
<table border=0 cellpadding=0 cellspacing=0 width=100%>
<tr><td bgcolor="#003399"><img src="/i/d.gif" width=1 height=1></td></tr>
<tr><TD align=center BGCOLOR="#FFFFFF">
<font face="ms sans serif,verdana,helvetica" size=1>
<b>Cotations</B><IMG SRC="http://stat.cybermonitor.com/boursorama_v?total" WIDTH=1 HEIGHT=1 BORDER=0><SCRIPT><!--
tps = new Date();
if (tps.getSeconds() < 5)
{document.write("<IMG SRC=\"http://stat.cybermonitor.com/boursorama_p?" + tps.getMinutes() + "0" + tps.getSeconds() + "_pap" + "\" WIDTH=\"1\" HEIGHT=\"1\">");}
// --></SCRIPT><NOSCRIPT><IMG SRC="http://stat.cybermonitor.com/boursorama_p?noscript_pap" WIDTH="1" HEIGHT="1"></NOSCRIPT></td></tr>
<tr><td bgcolor="#003399"><img src="/i/d.gif" width=1 height=1></td></tr>
<tr><td>
<font face="ms sans serif,verdana,helvetica" size=1>
<B><a href="/indices/indices.phtml">Indices</a></B> / <B><a href="/indices/futures.phtml">Futures</a><BR>
<img src="/i/d.gif" height=4 width=1 border=0><br>
<a href="/palmares/palmares.phtml?MARCHE=SRD&VARIATION=hausse&PERIODE=veille">Palmarès</a><BR>
<img src="/i/d.gif" height=4 width=1 border=0><br>
<a href="/privatisees.phtml">Privatisées</a><BR>
<table border=0 cellpadding=0 cellspacing=0 width=100%>
<TR><TD><img src="/i/d.gif" height=4 width=1 border=0><BR></TD></TR>
<TR bgcolor="#003399"><TD><font face="ms sans serif,verdana,helvetica" size=1 color="#FFFFFF"><B>Cours de A à Z</B></TD></TR></TABLE>
<img src="/i/d.gif" height=2 width=1 border=0><br>
<a href="/devises/devises.phtml">Devises</a></B> / <B><a href="/devises/taux_euribor.phtml">Taux</a><BR>
<img src="/i/d.gif" height=4 width=1 border=0><br>
<a href="/warrants/warrants_actions_fr.phtml">Warrants</a><BR>
<img src="/i/d.gif" height=4 width=1 border=0><br>
<a href="/opcvm/opcvm_index.phtml">Sicav et Fcp</a><BR>
<img src="/i/d.gif" height=4 width=1 border=0><br>
<a href="/indicateurs/advance_decline.phtml">Indicateurs</a><BR>
<img src="/i/d.gif" height=6 width=1 border=0><br>
</td></tr>
<tr><td bgcolor="#003399"><img src="/i/d.gif" width=1 height=1></td></tr>
<tr><TD align=center BGCOLOR="#FFFFFF">
<font face="ms sans serif,verdana,helvetica" size=1>
<B>Informations</B></td></tr>
<tr><td bgcolor="#003399"><img src="/i/d.gif" width=1 height=1></td></tr>
<tr><td><font face="ms sans serif,verdana,helvetica" size=1>
<b>
<A HREF="/infos/actualites/actu_marches.phtml">Actualités</a><BR>
<img src="/i/d.gif" height=4 width=1 border=0><br>
<A HREF="/infos/calendrier.phtml">Calendrier</a><BR>
<img src="/i/d.gif" height=4 width=1 border=0><br>
<A HREF="/infos/introductions.phtml">Introductions</a><BR>
<img src="/i/d.gif" height=6 width=1 border=0><br>
</td></tr>
<tr><td bgcolor="#003399"><img src="/i/d.gif" width=1 height=1></td></tr>
<tr><TD align=center BGCOLOR="#FFFFFF">
<font face="ms sans serif,verdana,helvetica" size=1>
<B>Analyses</B></td></tr>
<tr><td bgcolor="#003399"><img src="/i/d.gif" width=1 height=1></td></tr>
<tr><td NOWRAP><font face="ms sans serif,verdana,helvetica" size=1>
<B>
<A href="/conseils/conseils_index.phtml">Conseils boursiers</A><BR>
<img src="/i/d.gif" height=4 width=1 border=0><br>
<A href="/conseils/anatech_index.phtml">Analyses techn.</A><BR>
<img src="/i/d.gif" height=4 width=1 border=0><br>
<A HREF="/conseils/sectorama/sectorama.phtml">Sectorama</a><BR>
<img src="/i/d.gif" height=4 width=1 border=0><br>
<A HREF="/conseils/focus/focus.phtml">Focus</a><BR>
<img src="/i/d.gif" height=4 width=1 border=0><br>
<A HREF="/conseils/pros/pros.phtml">L'oeil des pros</a><BR>
<img src="/i/d.gif" height=6 width=1 border=0><br>
</B>
<tr><td bgcolor="#003399"><img src="/i/d.gif" width=1 height=1></td></tr>
<tr><TD align=center BGCOLOR="#FFFFFF">
<font face="ms sans serif,verdana,helvetica" size=1>
<B>International</B></td></tr>
<tr><td bgcolor="#003399"><img src="/i/d.gif" width=1 height=1></td></tr>
<tr><td><font face="ms sans serif,verdana,helvetica" size=1>
<b>
<A HREF="/international/international.phtml">Résumé</a><BR>
<img src="/i/d.gif" height=4 width=1 border=0><br>
<A HREF="/international/international_palmares.phtml">Palmarès</a><BR>
<img src="/i/d.gif" height=4 width=1 border=0><br>
<A HREF="/international/international_az.phtml">Cours de A à Z</a><BR>
<img src="/i/d.gif" height=4 width=1 border=0><br>
<A HREF="/international/actu_intern_index.phtml">Actualités</a><BR>
<img src="/i/d.gif" height=6 width=1 border=0><br>
</td></tr>
<tr><td bgcolor="#003399"><img src="/i/d.gif" width=1 height=1></td></tr>
<TR><TD align=center BGCOLOR="#FFFFFF"><font face="ms sans serif,verdana,helvetica" size=1><B>Campus</B></TD></TR>
<TR><TD bgColor=#003399><IMG height=1 src="/i/d.gif" width=1></TD></TR>
<TR>
<TD noWrap><font face="ms sans serif,verdana,helvetica" size=1><B>
<A href="/campus/guide/guide-de-la-bourse.phtml">Guide de la bourse</A><BR>
<img src="/i/d.gif" height=4 width=1 border=0><br>
<A HREF="/campus/fiscalite/essentiel.phtml">Fiscalité</a><BR>
<IMG border=0 height=6 src="/i/d.gif" width=1><BR>
</TD></TR>
<TR><TD bgColor=#003399><IMG height=1 src="/i/d.gif" width=1></TD></TR>
<TR>
<TD align=CENTER BGCOLOR="#C8C8C8"><font face="ms sans serif,verdana,helvetica" size=1><B>Aide</B></TD></TR>
<TR><TD bgColor=#003399><IMG height=1 src="/i/d.gif" width=1></TD></TR>
<TR>
<TD NOWRAP>
<font face="ms sans serif,verdana,helvetica" size=1><B>
<A href="/aide/aide.phtml">Quest./Rép.</A><BR>
<IMG border=0 height=4 src="/i/d.gif" width=1><BR>
<A HREF="/aide/motdepasse_email.phtml">Mot de passe</A><BR>
<IMG border=0 height=4 src="/i/d.gif" width=1><BR>
<A href="/aide/surfezplusvite.phtml">Surfez + vite</A><BR>
<IMG border=0 height=4 src="/i/d.gif" width=1><BR>
<A href="/contact/support.phtml">Contact</A><BR>
<IMG border=0 height=6 src="/i/d.gif" width=1><BR></TD></TR>
</TABLE></TD>
<TD width=1 BGCOLOR="#003399"><IMG SRC="/i/d.gif" WIDTH="1" HEIGHT="1" BORDER="0"></TD>
<TD width=2><IMG SRC="/i/d.gif" WIDTH="2" HEIGHT="1" border=0></TD>

<td valign=top>
<!-- CONTENU -->
<CENTER>
<!-- PUB TAG1-->
<table width=468 border=0 cellspacing=0 cellpadding=0><tr><td>
<NOLAYER>
<IFRAME SRC="http://ad.fr.doubleclick.net/adi/ad.boursorama.com/coursaz;cat=coursaz;sz=468x60;ord=994846627?" width=468 height=60 marginwidth=0 marginheight=0 hspace=0 vspace=0 frameborder=0 scrolling=no>
<A HREF="http://ad.fr.doubleclick.net/jump/ad.boursorama.com/coursaz;cat=coursaz;sz=468x60;ord=994846627?" target="_blank">
<IMG SRC="http://ad.fr.doubleclick.net/ad/ad.boursorama.com/coursaz;cat=coursaz;sz=468x60;ord=994846627?" border=0></A>
</IFRAME>
</NOLAYER>
<ilayer id=ph1 visibility=hide width=468 height=60></ilayer>
<SCRIPT></SCRIPT>
</td></tr></table>
<!-- /PUB TAG1-->
</CENTER>


<form action="cours_az.phtml" NAME="cours_az">
<!-- PETIT LOGO -->
<table border=0 width=100%>
<tr>
<td>
<a href="/index.phtml"><img src="/i/sublogo.gif" alt="Accès direct page d'accueil" width="330" height="35" border="0"></a>
</td>
<td valign=middle align=right><font face="ms sans serif,verdana,helvetica" size=1 color="003399"><B>12:17<BR>Mercredi 11 Juillet 2001</B></td>
</tr>
</table>
<!-- /PETIT LOGO -->
<!-- MENU PALMARES -->
<table border="0" cellpadding="0" cellspacing="0" width=100%>
<TR><TD valign=top COLSPAN="3"><font face="ms sans serif,verdana,arial" size=2 color="003399"><B>Cours de A à Z</B></font></TD></TR>
<tr bgcolor="#999999" height=1><td valign=top COLSPAN=3><img src="/i/dot_line.gif" vspace=0 border=0 valign=center width=1 height=1></td></tr>
<tr bgcolor="#ffe700"><td COLSPAN=3><font face="ms sans serif,verdana,helvetica" size=2 color="003399">
<B>Par marché</B>
 | 
<a href="secteurs.phtml">Par secteur</A> <font color="#c00000" face="arial,helvetica" size=1>Nouveau !</font>
 | 
<a href="regions.phtml">Par région</a> <font color="#c00000" face="arial,helvetica" size=1>Nouveau !</font>
</TD></TR>

<td valign=middle><FONT  FACE="ms sans serif,verdana,helvetica" SIZE=2>Choisissez un marché</font></td>
<td>
<SELECT NAME="MARCHE">
<OPTION VALUE="SRD">Valeurs éligibles au SRD</OPTION>
<OPTION VALUE="1001">Premier Marché France</OPTION>
<OPTION VALUE="1004">Premier Marché Etranger</OPTION>
<OPTION VALUE="1002">Second Marché</OPTION>
<OPTION VALUE="1003">Nouveau Marché</OPTION>
<OPTION VALUE="1005">Marché libre</OPTION>
<OPTION VALUE="1007">Indices Paris</OPTION>
<OPTION VALUE="1006">Warrants</OPTION>
<OPTION VALUE="1008">Obligations</OPTION>
<OPTION VALUE="1011">Trackers</OPTION>
<OPTION VALUE="CAC40">Indice CAC 40</OPTION>
<OPTION VALUE="SBF120">Indice SBF 120</OPTION>
<OPTION VALUE="SBF250">Indice SBF 250</OPTION>
</SELECT></td>
<td><input type="image" value="get" name="get" width="85" height="22" src="/i/afficher.gif" border="0">
</td>
</tr>

</table>
<script language="JavaScript">
  select_value(document.cours_az.MARCHE,"SRD");
</script>
<!-- /MENU-->

<!-- CHOIX LETTRE -->
<CENTER><table border=0>
<tr>
<td valign=top><font face="ms sans serif,verdana,helvetica" size=2>
<B>
<A HREF="cours_az.phtml?MARCHE=SRD&LETTRE=A">A</A>
<A HREF="cours_az.phtml?MARCHE=SRD&LETTRE=B">B</A>
<A HREF="cours_az.phtml?MARCHE=SRD&LETTRE=C">C</A>
<A HREF="cours_az.phtml?MARCHE=SRD&LETTRE=D">D</A>
<A HREF="cours_az.phtml?MARCHE=SRD&LETTRE=E">E</A>
<A HREF="cours_az.phtml?MARCHE=SRD&LETTRE=F">F</A>
<A HREF="cours_az.phtml?MARCHE=SRD&LETTRE=G">G</A>
<A HREF="cours_az.phtml?MARCHE=SRD&LETTRE=H">H</A>
<A HREF="cours_az.phtml?MARCHE=SRD&LETTRE=I">I</A>
<A HREF="cours_az.phtml?MARCHE=SRD&LETTRE=J">J</A>
<A HREF="cours_az.phtml?MARCHE=SRD&LETTRE=K">K</A>
<A HREF="cours_az.phtml?MARCHE=SRD&LETTRE=L">L</A>
<A HREF="cours_az.phtml?MARCHE=SRD&LETTRE=M">M</A>
<A HREF="cours_az.phtml?MARCHE=SRD&LETTRE=N">N</A>
<A HREF="cours_az.phtml?MARCHE=SRD&LETTRE=O">O</A>
<A HREF="cours_az.phtml?MARCHE=SRD&LETTRE=P">P</A>
<A HREF="cours_az.phtml?MARCHE=SRD&LETTRE=Q">Q</A>
<A HREF="cours_az.phtml?MARCHE=SRD&LETTRE=R">R</A>
<A HREF="cours_az.phtml?MARCHE=SRD&LETTRE=S">S</A>
<A HREF="cours_az.phtml?MARCHE=SRD&LETTRE=T">T</A>
<A HREF="cours_az.phtml?MARCHE=SRD&LETTRE=U">U</A>
<A HREF="cours_az.phtml?MARCHE=SRD&LETTRE=V">V</A>
<A HREF="cours_az.phtml?MARCHE=SRD&LETTRE=W">W</A>
<A HREF="cours_az.phtml?MARCHE=SRD&LETTRE=X">X</A>
<A HREF="cours_az.phtml?MARCHE=SRD&LETTRE=Y">Y</A>
<A HREF="cours_az.phtml?MARCHE=SRD&LETTRE=Z">Z</A>
</B>
</td>
</tr>
</table>
</CENTER><!-- /CHOIX LETTRE -->

<!-- TABLEAU COURS-->
<table border=0 cellpadding=0 cellspacing=1 width=100%>
<tr bgcolor="#003399"><td  colspan=8><font face="ms sans serif,verdana,helvetica" size=1 color="FFFFFF"><B>Valeurs éligibles au Service de Règlement Différé</B></font></td>
</tr>
<tr>
<td>
<font face="ms sans serif,verdana,helvetica" size=1>Libellé</font>
</td>
<td align=center>
<font face="ms sans serif,verdana,helvetica" size=1>Dernier <img src="/i/euro6x9.gif" width=6 height=9></font>
</td>
<td align=center>
<font face="ms sans serif,verdana,helvetica" size=1>Var.</font>
</td>
<td align=center>
<font face="ms sans serif,verdana,helvetica" size=1>Dernier F</font>
</td>
<td align=center>
<font face="ms sans serif,verdana,helvetica" size=1>Ouvert.</font>
</td>
<td align=center>
<font face="ms sans serif,verdana,helvetica" size=1>+ Haut</font>
</td>
<td align=center>
<font face="ms sans serif,verdana,helvetica" size=1>+ Bas</font>
</td>
<td align=center>
<font face="ms sans serif,verdana,helvetica" size=1>Vol. titres</font>
</td>
</tr>
<tr bgcolor="#999999" height=1>
<td valign=top colspan=8><img src="/i/dot_line.gif" vspace=0 border=0 valign=center width=1 height=1></td></tr>
<tr>
<td align=left><font face="ms sans serif,verdana,helvetica" size=1><A HREF="/cours33.phtml?symbole=1rTCAC">CAC 40 MASTER UNIT</A></font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>50</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1 color=#880000>-0.89%</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>327.98</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>49.75</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>50.3</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>49.7</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>421196</font></td>
</tr>
<tr BGCOLOR="#EEEEEE">
<td align=left><font face="ms sans serif,verdana,helvetica" size=1><A HREF="/cours33.phtml?symbole=1rPAN">CANAL +</A></font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>3.5</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1 color=#880000>-0.85%</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>22.96</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>3.5</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>3.57</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>3.48</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>110341</font></td>
</tr>
<tr>
<td align=left><font face="ms sans serif,verdana,helvetica" size=1><A HREF="/cours33.phtml?symbole=1rPCAP">CAP GEMINI</A></font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>78</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1 color=#880000>-0.70%</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>511.65</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>77.1</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>79.1</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>77</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>178898</font></td>
</tr>
<tr BGCOLOR="#EEEEEE">
<td align=left><font face="ms sans serif,verdana,helvetica" size=1><A HREF="/cours33.phtml?symbole=1rPCRL">CARBONE LORRAINE</A></font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>42.8</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1 color=#880000>-0.93%</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>280.75</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>43.2</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>43.2</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>42.8</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>7784</font></td>
</tr>
<tr>
<td align=left><font face="ms sans serif,verdana,helvetica" size=1><A HREF="/cours33.phtml?symbole=1rPCA">CARREFOUR</A></font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>59.7</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1 color=#880000>-1.08%</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>391.61</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>59.8</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>60.7</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>59.35</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>597936</font></td>
</tr>
<tr BGCOLOR="#EEEEEE">
<td align=left><font face="ms sans serif,verdana,helvetica" size=1><A HREF="/cours33.phtml?symbole=1rPCO">CASINO GUICHARD</A></font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>96.05</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1 color=#008800>+0.31%</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>630.05</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>95.85</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>96.7</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>95.75</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>68830</font></td>
</tr>
<tr>
<td align=left><font face="ms sans serif,verdana,helvetica" size=1><A HREF="/cours33.phtml?symbole=1rPCY">CASTORAMA DUBOIS</A></font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>62.8</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1 color=#880000>-1.88%</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>411.94</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>61.2</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>63.1</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>61.2</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>88783</font></td>
</tr>
<tr BGCOLOR="#EEEEEE">
<td align=left><font face="ms sans serif,verdana,helvetica" size=1><A HREF="/cours33.phtml?symbole=1rPCOL">CEREOL</A></font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>22.07</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1 color=#008800>+0.32%</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>144.77</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>22.5</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>22.5</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>21.91</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>22942</font></td>
</tr>
<tr>
<td align=left><font face="ms sans serif,verdana,helvetica" size=1><A HREF="/cours33.phtml?symbole=1rPCAR">CERESTAR</A></font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>22.75</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1 color=#880000>-3.19%</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>149.23</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>23.45</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>23.45</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>21.86</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>22311</font></td>
</tr>
<tr BGCOLOR="#EEEEEE">
<td align=left><font face="ms sans serif,verdana,helvetica" size=1><A HREF="/cours33.phtml?symbole=1rPCW">CGIP</A></font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>34.09</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1 color=#880000>-0.61%</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>223.62</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>34.15</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>34.15</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>33.65</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>39303</font></td>
</tr>
<tr>
<td align=left><font face="ms sans serif,verdana,helvetica" size=1><A HREF="/cours33.phtml?symbole=1rPCDI">CHRISTIAN DIOR</A></font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>40.6</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1 color=#008800>+0.25%</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>266.32</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>40.6</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>40.84</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>40.02</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>67478</font></td>
</tr>
<tr BGCOLOR="#EEEEEE">
<td align=left><font face="ms sans serif,verdana,helvetica" size=1><A HREF="/cours33.phtml?symbole=1rPCMA">CIMENTS FRANCAIS</A></font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>52</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1 color=#880000>-1.33%</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>341.10</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>51.75</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>52.45</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>51.75</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>1230</font></td>
</tr>
<tr>
<td align=left><font face="ms sans serif,verdana,helvetica" size=1><A HREF="/cours33.phtml?symbole=1rPCLR">CLARINS</A></font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>87.8</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1 color=#880000>-0.23%</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>575.93</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>88</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>88.6</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>87.1</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>3323</font></td>
</tr>
<tr BGCOLOR="#EEEEEE">
<td align=left><font face="ms sans serif,verdana,helvetica" size=1><A HREF="/cours33.phtml?symbole=1rPCU">CLUB MEDITERRANEE</A></font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>66.35</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1 color=#880000>-1.19%</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>435.23</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>67</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>67</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>65.65</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>27438</font></td>
</tr>
<tr>
<td align=left><font face="ms sans serif,verdana,helvetica" size=1><A HREF="/cours33.phtml?symbole=1rPCNP">CNP ASSURANCES</A></font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>36.8</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1 color=#880000>-0.81%</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>241.39</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>37</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>37.25</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>36.8</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>7006</font></td>
</tr>
<tr BGCOLOR="#EEEEEE">
<td align=left><font face="ms sans serif,verdana,helvetica" size=1><A HREF="/cours33.phtml?symbole=1rPCFC">COFACE</A></font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>81.4</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1 color=#880000>-0.12%</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>533.95</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>80.2</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>81.45</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>80.2</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>972</font></td>
</tr>
<tr>
<td align=left><font face="ms sans serif,verdana,helvetica" size=1><A HREF="/cours33.phtml?symbole=1rPCFI">COFLEXIP</A></font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>167</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1 color=#880000>-1.76%</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>1095.45</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>170</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>170.5</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>165</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>67335</font></td>
</tr>
<tr BGCOLOR="#EEEEEE">
<td align=left><font face="ms sans serif,verdana,helvetica" size=1><A HREF="/cours33.phtml?symbole=1rPRE">COLAS</A></font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>65.2</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1 color=#008800>+0.23%</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>427.68</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>65.2</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>66.5</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>65.2</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>176</font></td>
</tr>
<tr>
<td align=left><font face="ms sans serif,verdana,helvetica" size=1><A HREF="/cours33.phtml?symbole=1rPCTL">COMPLETEL EUROPE</A></font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>2.6</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1 color=#008800>+7.88%</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>17.05</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>2.25</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>2.67</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>2.19</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>441921</font></td>
</tr>
<tr BGCOLOR="#EEEEEE">
<td align=left><font face="ms sans serif,verdana,helvetica" size=1><A HREF="/cours33.phtml?symbole=1rPCL">CREDIT LYONNAIS</A></font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>44.2</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1 color=#880000>-0.56%</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>289.93</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>44</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>44.4</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>43.71</font></td>
<td align=center><font face="ms sans serif,verdana,helvetica" size=1>387499</font></td>
</tr>
</table>
<!-- /TABLEAU COURS-->

<!-- CHOIX LETTRE -->
<CENTER><table border=0>
<tr>
<td valign=top><font face="ms sans serif,verdana,helvetica" size=2>
<B>
<A HREF="cours_az.phtml?MARCHE=SRD&LETTRE=A">A</A>
<A HREF="cours_az.phtml?MARCHE=SRD&LETTRE=B">B</A>
<A HREF="cours_az.phtml?MARCHE=SRD&LETTRE=C">C</A>
<A HREF="cours_az.phtml?MARCHE=SRD&LETTRE=D">D</A>
<A HREF="cours_az.phtml?MARCHE=SRD&LETTRE=E">E</A>
<A HREF="cours_az.phtml?MARCHE=SRD&LETTRE=F">F</A>
<A HREF="cours_az.phtml?MARCHE=SRD&LETTRE=G">G</A>
<A HREF="cours_az.phtml?MARCHE=SRD&LETTRE=H">H</A>
<A HREF="cours_az.phtml?MARCHE=SRD&LETTRE=I">I</A>
<A HREF="cours_az.phtml?MARCHE=SRD&LETTRE=J">J</A>
<A HREF="cours_az.phtml?MARCHE=SRD&LETTRE=K">K</A>
<A HREF="cours_az.phtml?MARCHE=SRD&LETTRE=L">L</A>
<A HREF="cours_az.phtml?MARCHE=SRD&LETTRE=M">M</A>
<A HREF="cours_az.phtml?MARCHE=SRD&LETTRE=N">N</A>
<A HREF="cours_az.phtml?MARCHE=SRD&LETTRE=O">O</A>
<A HREF="cours_az.phtml?MARCHE=SRD&LETTRE=P">P</A>
<A HREF="cours_az.phtml?MARCHE=SRD&LETTRE=Q">Q</A>
<A HREF="cours_az.phtml?MARCHE=SRD&LETTRE=R">R</A>
<A HREF="cours_az.phtml?MARCHE=SRD&LETTRE=S">S</A>
<A HREF="cours_az.phtml?MARCHE=SRD&LETTRE=T">T</A>
<A HREF="cours_az.phtml?MARCHE=SRD&LETTRE=U">U</A>
<A HREF="cours_az.phtml?MARCHE=SRD&LETTRE=V">V</A>
<A HREF="cours_az.phtml?MARCHE=SRD&LETTRE=W">W</A>
<A HREF="cours_az.phtml?MARCHE=SRD&LETTRE=X">X</A>
<A HREF="cours_az.phtml?MARCHE=SRD&LETTRE=Y">Y</A>
<A HREF="cours_az.phtml?MARCHE=SRD&LETTRE=Z">Z</A>
</B>
</td>
</tr>
</table>
</CENTER><!-- /CHOIX LETTRE -->
</form>
<!-- RECHERCHE -->
<form name="recherche" onSubmit="return goto_location(this.type_info.selectedIndex,this.code.value,this.choix_bourse.selectedIndex,this.choix_bourse.options[this.choix_bourse.selectedIndex].value)">
<table border="0" cellpadding="1" cellspacing="0" width=100%>
<tr>
<td colspan=4><font face="ms sans serif,verdana,helvetica" size=2 color="003399"><B>Nouvelle recherche</B></font>
</td></tr>
<tr bgcolor="#FFE700">
<td><font face="ms sans serif,verdana,helvetica" size=1>Code, symbole ou libellé</font></td>
<td colspan=3><font face="ms sans serif,verdana,helvetica" size=1>Pays</font></td>
</tr>
<tr valign=middle>
<td><input type="TEXT" name="code" value="" size=14></td>
<td><SELECT NAME="choix_bourse" onchange="MAJListePage(document.recherche.type_info,this.selectedIndex)">
<OPTION VALUE="pays=33">&nbsp;France
<OPTION VALUE="pays=49">&nbsp;Allemagne
<OPTION VALUE="pays=32">&nbsp;Belgique
<OPTION VALUE="pays=2">&nbsp;Canada
<OPTION VALUE="pays=34">&nbsp;Espagne
<OPTION VALUE="pays=1">&nbsp;Etats-Unis
<OPTION VALUE="pays=39">&nbsp;Italie
<OPTION VALUE="pays=31">&nbsp;Pays-Bas
<OPTION VALUE="pays=41">&nbsp;Suisse
<OPTION VALUE="pays=44">&nbsp;UK
<OPTION VALUE="bourse=4404">&nbsp;Devises
</SELECT>
</td>
<td><SELECT NAME="type_info">
<OPTION VALUE="cours">Cours en direct&nbsp;
<OPTION VALUE="graph">Graphique
<OPTION VALUE="forum">Forum
<OPTION VALUE="fondam">Consensus
<OPTION VALUE="actu">Actualités
<OPTION VALUE="profil">Profil
<OPTION VALUE="conseils">Conseils
</SELECT></td>
<td><input type="image" value="get" name="get" width="85" height="22" src="/i/afficher.gif" border="0"></td>
</form>
</tr>
</table>


<!-- /RECHERCHE -->
<P>

<hr size=1 width=98%>
<font face="ms sans serif,verdana,helvetica" size=1>
<CENTER><a href="/divers/avertissement.phtml">Copyright © 1998-2001 Finance Net</a> - <a href="/contact/support.phtml">Contactez-nous</a></font><BR>
<font face="arial,helvetica" size=1>Cours différés d'au moins 15 mn (Paris, Nasdaq, Francfort, Londres, Milan, Madrid, Bruxelles, Amsterdam, Toronto),
20 mn (NYSE) ou 30 mn (Zürich). Indices Paris, Bruxelles, Amsterdam, Francfort en temps réel.<br>
Source <a href="/services/spcomstock/index.phtml">Standard & Poor's Comstock</a> et <a href="http://www.fininfo.fr" target="_blank">Fininfo</a>. Consultez notre <a href="/divers/avertissement.phtml">avertissement légal</a>.<BR>
Retrouvez Boursorama par téléphone 24h/24 au 0892 69 24 24 (2,21 frf/mn)<BR> et sur Minitel 3615 BOURSORAMA (1,28 frf/mn)
</font></CENTER>
</td>
<TD width=1><IMG border=0 height=1 src="/i/d.gif" width=1></TD>
<TD width=1 bgcolor="#003399"><IMG border=0 height=1 src="/i/d.gif" width=1></TD>
<TD bgColor=#EEEEEE vAlign=top>
<TABLE border=0 cellPadding=0 cellSpacing=0>
<TR><TD bgColor=#003399><IMG height=1 src="/i/d.gif" width=1></TD></TR>
<TR><TD align=CENTER bgColor=#FFE700><font face="ms sans serif,verdana,helvetica" size=1><B>Communauté</B></TD></TR>
<TR><TD bgColor=#003399><IMG height=1 src="/i/d.gif" width=1></TD></TR>
<tr>
<td NOWRAP>
<font face="ms sans serif,verdana,helvetica" size=1>
&nbsp;&nbsp;<B><A href="/forum/forums_index.phtml">Forums</A></B><BR>
<IMG border=0 height=4 src="/i/d.gif" width=1><BR>
&nbsp;&nbsp;<B><A href="/forum/membres/top_forums.phtml">Top forums</A></B><BR>
<IMG border=0 height=4 src="/i/d.gif" width=1><BR>
&nbsp;&nbsp;<B><A href="/forum/forums_last.phtml">Derniers msg.</A></B><BR>
<IMG border=0 height=4 src="/i/d.gif" width=1><BR>
&nbsp;&nbsp;<B><A href="/infos/membres/top_consensus.phtml">Top consensus</A></B><BR>
<IMG border=0 height=4 src="/i/d.gif" width=1><BR>
&nbsp;&nbsp;<B><A href="/votreinvite/presentation.phtml">Votre invité</A></B><BR>
<IMG border=0 height=4 src="/i/d.gif" width=1><BR>
&nbsp;&nbsp;<B><A href="http://jeu.boursorama.com/index.phtml">Jeu Boursorama</A></B><BR>
<IMG border=0 height=6 src="/i/d.gif" width=1><BR>
</TD></TR>
</td>
</tr>
<TR><TD bgColor=#003399><IMG height=1 src="/i/d.gif" width=1></TD></TR>
<TR><TD align=CENTER bgColor=#FFE700 nowrap><font face="ms sans serif,verdana,helvetica" size=1>&nbsp;<B>Mon Boursorama</B>&nbsp;</TD></TR>
<TR><TD bgColor=#003399><IMG height=1 src="/i/d.gif" width=1></TD></TR>
<tr>
<td NOWRAP>
<font face="ms sans serif,verdana,helvetica" size=1>
&nbsp;&nbsp;<B><A href="/liste/liste.phtml">Ma liste</A></B><BR>
<IMG border=0 height=4 src="/i/d.gif" width=1><BR>
&nbsp;&nbsp;<B><A href="/portefeuille/portefeuille.phtml">Mon portefeuille</A></B>&nbsp;<BR>
<IMG border=0 height=4 src="/i/d.gif" width=1><BR>
&nbsp;&nbsp;<B><A href="/email/">Mon email</A></B><BR>
<IMG border=0 height=4 src="/i/d.gif" width=1><BR>
&nbsp;&nbsp;<B><A href="/membres/mes_graphiques.phtml">Mes paramètres</A></B><BR>
<IMG border=0 height=4 src="/i/d.gif" width=1><BR>
&nbsp;&nbsp;<B><A href="/membres/mon_profil.phtml">Mon profil</A></B><BR>
<IMG border=0 height=4 src="/i/d.gif" width=1><BR>
&nbsp;&nbsp;<B><A href="/deconnexion.phtml">Déconnexion</A></B><BR>
<IMG border=0 height=4 src="/i/d.gif" width=1><BR>
&nbsp;&nbsp;<B><A href="/enregistrement/enregistrement_index.phtml"><FONT color=#C00000>Devenir membre</font></A></B><BR>
<IMG border=0 height=6 src="/i/d.gif" width=1><BR>
</TD></TR>
<TR><TD bgColor=#003399><IMG height=1 src="/i/d.gif" width=1></TD></TR>
<TR><TD>
<font face="ms sans serif,verdana,helvetica" size=1>
<CENTER><B><A href="/services/trading/trading.phtml">Trading Online</a></B></CENTER>
</font>
<IMG border=0 height=3 src="/i/d.gif" width=1><BR>
</TD></TR>
<TR><TD bgColor=#003399><IMG height=1 src="/i/d.gif" width=1></TD></TR>
<TR><TD align=CENTER BGCOLOR="#FFFFFF" nowrap><font face="arial,helvetica" size=1>&nbsp;<B>Pratique</B>&nbsp;</TD></TR>
<TR><TD bgColor=#003399><IMG height=1 src="/i/d.gif" width=1></TD></TR>
<TR>
<td NOWRAP>
<font face="arial,helvetica" size=1>
&nbsp;&nbsp;<B><A href="/pratique/actu/index.phtml">Actualités</A></B><BR>
<IMG border=0 height=2 src="/i/d.gif" width=1><BR>
&nbsp;&nbsp;<B><A href="/pratique/meteo/index.phtml">Météo</A></B><BR>
<IMG border=0 height=4 src="/i/d.gif" width=1><BR>
</TD></TR>

<TR><TD bgColor=#003399><IMG height=1 src="/i/d.gif" width=1></TD></TR>
<TR><TD align=CENTER BGCOLOR="#FFFFFF" nowrap><font face="arial,helvetica" size=1>&nbsp;<B>Multi-accès</B>&nbsp;</TD></TR>
<TR><TD bgColor=#003399><IMG height=1 src="/i/d.gif" width=1></TD></TR>
<TR>
<td NOWRAP>
<font face="arial,helvetica" size=1>
&nbsp;&nbsp;<B><A href="/multi/minitel/3615boursorama.phtml">3615 boursorama</A></B><BR>
<IMG border=0 height=2 src="/i/d.gif" width=1><BR>
&nbsp;&nbsp;<B><A href="/multi/telephone/0892-69-24-24.phtml">0892 69 24 24</A></B><BR>
<IMG border=0 height=2 src="/i/d.gif" width=1><BR>
&nbsp;&nbsp;<B><A href="/multi/wap/index.phtml">Mobile/WAP</A></B><BR>
<IMG border=0 height=2 src="/i/d.gif" width=1><BR>
&nbsp;&nbsp;<B><A href="/multi/pda/index.phtml">Mobile/PDA</A></B><BR>
<IMG border=0 height=4 src="/i/d.gif" width=1><BR>
</TD></TR>
<TR><TD bgColor=#003399><IMG height=1 src="/i/d.gif" width=1></TD></TR>
<TR><TD align=CENTER bgColor=#FFFFFF nowrap><font face="arial,helvetica" size=1>&nbsp;<B>Investissez</B>&nbsp;</TD></TR>
<TR><TD bgColor=#003399><IMG height=1 src="/i/d.gif" width=1></TD></TR>
<TR>
<TD NOWRAP>
<font face="arial,helvetica" size=1>
&nbsp;&nbsp;<B><A href="/investissez/certificats/certificats.phtml">Certificats</A></B><BR>
<IMG border=0 height=4 src="/i/d.gif" width=1><BR>
</TD></TR>
<TR><TD bgColor=#003399><IMG height=1 src="/i/d.gif" width=1></TD></TR>
<TR>
<TD>
<font size=1 face="arial,verdana,helvetica">
&nbsp; &nbsp; <A href="/communication/">Info Publicité</A><BR>
<IMG border=0 height=4 src="/i/d.gif" width=1><BR>
&nbsp; &nbsp; <A href="http://www.finance-net.fr/presse.phtml" target=_blank>Presse</A><BR>
<IMG border=0 height=4 src="/i/d.gif" width=1><BR>
&nbsp; &nbsp; <A href="http://www.finance-net.fr/jobs/jobs.phtml" target=_blank>JOBS</A><BR>
<BR>
&nbsp; &nbsp; Sites Finance Net<BR>
<IMG border=0 height=4 src="/i/d.gif" width=1><BR>
&nbsp; &nbsp; <A href="http://www.finance-net.com/" target=_blank>Finance-Net.com</A><BR>
<IMG border=0 height=4 src="/i/d.gif" width=1><BR>
&nbsp; &nbsp; <A href="http://www.finance-net.fr/" target=_blank>La société</A><BR>
</font>
</TD>
</TR>
</TABLE>
</TD>
</tr>
</table>
</center>
<layer src="http://ad.fr.doubleclick.net/adl/ad.boursorama.com/coursaz;cat=coursaz;sz=468x60;ord=994846627?" visibility=hide
onload="moveToAbsolute(ph1.pageX, ph1.pageY);visibility='show';"></layer>
<layer src="http://ad.fr.doubleclick.net/adl/ad.boursorama.com/menu100x60;cat=menu100x60;sz=100x60;ord=994846627?" visibility=hide
onload="moveToAbsolute(ph2.pageX, ph2.pageY);visibility='show';"></layer>
</BODY>
</HTML>









