


struct VFNamesWithHashCode
{
	char* vfname;
	VFNAME id;
	FUNCPTR func;
	int hashcode;
} hashtable[325] =
{
	{ "ABSCDSBasketTranche",VF_ABSCDSBasketTranche, &accept, 0, },
	{ "ABSCreditDefaultSwap",VF_ABSCreditDefaultSwap,&accept, 0 },
	{ "AlgorithmiclndexBasketTotalReturn",VF_AlgorithmiclndexBasketTotalReturn,&accept, 0 },
	{ "AlgorithmicIndexBasketTotalReturn2",VF_AlgorithmicIndexBasketTotalReturn2,&accept, 0 },
	{ "AlgorithmicIndexBasketTotalReturnOption",VF_AlgorithmicIndexBasketTotalReturnOption,&accept, 0 },
	{ "AlgorithmicIndexLiborOption",VF_AlgorithmicIndexLiborOption,&accept, 0 },
	{ "AlgorithmicIndexTotalReturn",VF_AlgorithmicIndexTotalReturn,&accept, 0 },
	{ "AlgorithmicIndexTotalReturnOption",VF_AlgorithmicIndexTotalReturnOption,&accept, 0 },
	{ "AnnuityOption3",VF_AnnuityOption3,&accept, 0 },
	{ "AsianDigitalQCMSLeg",VF_AsianDigitalQCMSLeg,&accept, 0 },
	{ "AsianSpreadOption",VF_AsianSpreadOption,&accept, 0 },
	{ "AutoCap",VF_AutoCap,&accept, 0 },
	{ "BarrierPRD",VF_BarrierPRD,&accept, 0 },
	{ "BarrierPRD2",VF_BarrierPRD2,&accept, 0 },
	{ "BarrierSwap",VF_BarrierSwap,&accept, 0 },
	{ "BasisSwap",VF_BasisSwap,&accept, 0 },
	{ "BasisSwapLegUntilDefault",VF_BasisSwapLegUntilDefault,&accept, 0 },
	{ "BasisSwapMtM",VF_BasisSwapMtM,&accept, 0 },
	{ "BasisSwapMtM2",VF_BasisSwapMtM2,&accept, 0 },
	{ "BasisSwaption",VF_BasisSwaption,&accept, 0 },
	{ "BermudanAsianSpreadOption",VF_BermudanAsianSpreadOption,&accept, 0 },
	{ "BermudanCDOCorridor",VF_BermudanCDOCorridor,&accept, 0 },
	{ "BermudanCorridor",VF_BermudanCorridor,&accept, 0 },
	{ "BermudanDoubleEquityCorridor",VF_BermudanDoubleEquityCorridor,&accept, 0 },
	{ "BermudanDoubleSpreadCorridor",VF_BermudanDoubleSpreadCorridor,&accept, 0 },
	{ "BermudanQuantoCorridor",VF_BermudanQuantoCorridor,&accept, 0 },
	{ "BermudanSpreadCorridor",VF_BermudanSpreadCorridor,&accept, 0 },
	{ "BermudanSwaption",VF_BermudanSwaption,&accept, 0 },
	{ "BermudanSwaption2",VF_BermudanSwaption2,&accept, 0 },
	{ "BermudanSwaption2BondLinked",VF_BermudanSwaption2BondLinked,&accept, 0 },
	{ "BermudanZeroSwaption",VF_BermudanZeroSwaption,&accept, 0 },
	{ "BestOflnflationAndEquity",VF_BestOflnflationAndEquity,&accept, 0 },
	{ "BondASMOption",VF_BondASMOption,&accept, 0 },
	{ "BondCashFlowsTrade",VF_BondCashFlowsTrade,&accept, 0 },
	{ "BondExchangeableASMOption",VF_BondExchangeableASMOption,&accept, 0 },
	{ "BondFixedASMOption",VF_BondFixedASMOption,&accept, 0 },
	{ "BondFutureOptionTrade",VF_BondFutureOptionTrade,&accept, 0 },
	{ "BondFutureTrade",VF_BondFutureTrade,&accept, 0 },
	{ "BondGapOption",VF_BondGapOption,&accept, 0 },
	{ "BondOption",VF_BondOption,&accept, 0 },
	{ "BondOptionTrade",VF_BondOptionTrade,&accept, 0 },
	{ "BondRepo",VF_BondRepo,&accept, 0 },
	{ "BondRepoCustom",VF_BondRepoCustom,&accept, 0 },
	{ "BondTrade",VF_BondTrade,&accept, 0 },
	{ "BradyBondTrade",VF_BradyBondTrade,&accept, 0 },
	{ "BradyFRNTrade",VF_BradyFRNTrade,&accept, 0 },
	{ "CallableBondAssetSwap",VF_CallableBondAssetSwap,&accept, 0 },
	{ "CallableCDOCorridor",VF_CallableCDOCorridor,&accept, 0 },
	{ "CallableCorridor",VF_CallableCorridor,&accept, 0 },
	{ "CallableCorridorBondLinked",VF_CallableCorridorBondLinked,&accept, 0 },
	{ "CallableCreditDefaultSwap",VF_CallableCreditDefaultSwap,&accept, 0 },
	{ "CallableDoubleSpreadCorridor",VF_CallableDoubleSpreadCorridor,&accept, 0 },
	{ "CallableDualReverseFloater",VF_CallableDualReverseFloater,&accept, 0 },
	{ "CallableDualSpread",VF_CallableDualSpread,&accept, 0 },
	{ "CallableEquityOption",VF_CallableEquityOption,&accept, 0 },
	{ "CallableFxIRSpreadOption",VF_CallableFxIRSpreadOption,&accept, 0 },
	{ "CallableFxTrade",VF_CallableFxTrade,&accept, 0 },
	{ "CallableLiborTrade",VF_CallableLiborTrade,&accept, 0 },
	{ "CallablePRD",VF_CallablePRD,&accept, 0 },
	{ "CallableQuantoCorridor",VF_CallableQuantoCorridor,&accept, 0 },
	{ "CallableRatchetCorridor",VF_CallableRatchetCorridor,&accept, 0 },
	{ "CallableRepoTrade",VF_CallableRepoTrade,&accept, 0 },
	{ "CallableReverseFloater",VF_CallableReverseFloater,&accept, 0 },
	{ "CallableRiskyAssetSwap",VF_CallableRiskyAssetSwap,&accept, 0 },
	{ "CallableRiskyFloatingAssetSwap",VF_CallableRiskyFloatingAssetSwap,&accept, 0 },
	{ "CallableRiskySpreadOption",VF_CallableRiskySpreadOption,&accept, 0 },
	{ "CallableSpreadCorridor",VF_CallableSpreadCorridor,&accept, 0 },
	{ "CallableSpreadOption",VF_CallableSpreadOption,&accept, 0 },
	{ "CapFloor",VF_CapFloor,&accept, 0 },
	{ "CashBalance",VF_CashBalance,&accept, 0 },
	{ "CashlndexOption",VF_CashlndexOption,&accept, 0 },
	{ "CD0Forward",VF_CD0Forward,&accept, 0 },
	{ "CDOofCDOs",VF_CDOofCDOs,&accept, 0 },
	{ "CDSBasketIndex",VF_CDSBasketIndex,&accept, 0 },
	{ "CDSBasketIndexCapFloor",VF_CDSBasketIndexCapFloor,&accept, 0 },
	{ "CDSBasketIndexCMSLeg",VF_CDSBasketIndexCMSLeg,&accept, 0 },
	{ "CDSBasketIndexOption",VF_CDSBasketIndexOption,&accept, 0 },
	{ "CDSBasketRollingIndexCapFloor",VF_CDSBasketRollingIndexCapFloor,&accept, 0 },
	{ "CDSBasketRollingIndexCMSLeg",VF_CDSBasketRollingIndexCMSLeg,&accept, 0 },
	{ "CDSBasketTranche",VF_CDSBasketTranche,&accept, 0 },
	{ "CDSBasketTranchProtectionTrade",VF_CDSBasketTranchProtectionTrade,&accept, 0 },
	{ "CDSPortfolio",VF_CDSPortfolio,&accept, 0 },
	{ "ChooserTarn",VF_ChooserTarn,&accept, 0 },
	{ "CMMForwardRateAgreement",VF_CMMForwardRateAgreement,&accept, 0 },
	{ "CMMLeg",VF_CMMLeg,&accept, 0 },
	{ "CMSDualRateOption",VF_CMSDualRateOption,&accept, 0 },
	{ "CMSLinkedIRRSwap",VF_CMSLinkedIRRSwap,&accept, 0 },
	{ "CMSMultiplier",VF_CMSMultiplier,&accept, 0 },
	{ "CMSSpreadHedged",VF_CMSSpreadHedged,&accept, 0 },
	{ "CMSTripleRateOption",VF_CMSTripleRateOption,&accept, 0 },
	{ "CMTCapFloor",VF_CMTCapFloor,&accept, 0 },
	{ "CMTLeg",VF_CMTLeg,&accept, 0 },
	{ "CMTLeg2",VF_CMTLeg2,&accept, 0 },
	{ "CommodityAPO",VF_CommodityAPO,&accept, 0 },
	{ "CommodityBasisSwap",VF_CommodityBasisSwap,&accept, 0 },
	{ "CommodityBasketOption",VF_CommodityBasketOption,&accept, 0 },
	{ "CommodityBasketSwap",VF_CommodityBasketSwap,&accept, 0 },
	{ "CommodityClearedAPO",VF_CommodityClearedAPO,&accept, 0 },
	{ "CommodityClearedBasisSwap",VF_CommodityClearedBasisSwap,&accept, 0 },
	{ "CommodityClearedGasForward",VF_CommodityClearedGasForward,&accept, 0 },
	{ "CommodityClearedPowerForward",VF_CommodityClearedPowerForward,&accept, 0 },
	{ "CommodityClearedSwap",VF_CommodityClearedSwap,&accept, 0 },
	{ "CommodityCompoAPO",VF_CommodityCompoAPO,&accept, 0 },
	{ "CommodityCompoSwap",VF_CommodityCompoSwap,&accept, 0 },
	{ "CommodityDerivedInstrumentPrice",VF_CommodityDerivedInstrumentPrice,&accept, 0 },
	{ "CommodityEnergyOption",VF_CommodityEnergyOption,&accept, 0 },
	{ "CommodityFloatingForward",VF_CommodityFloatingForward,&accept, 0 },
	{ "CommodityFuture",VF_CommodityFuture,&accept, 0 },
	{ "CommodityFutureOption",VF_CommodityFutureOption,&accept, 0 },
	{ "CommodityFutureOptionTrade",VF_CommodityFutureOptionTrade,&accept, 0 },
	{ "CommodityFutureTrade",VF_CommodityFutureTrade,&accept, 0 },
	{ "CommodityGasForward",VF_CommodityGasForward,&accept, 0 },
	{ "CommodityGasStorage",VF_CommodityGasStorage,&accept, 0 },
	{ "Commodity0ption",VF_Commodity0ption,&accept, 0 },
	{ "Commodity0ptionTrade",VF_Commodity0ptionTrade,&accept, 0 },
	{ "CommodityPowerForward",VF_CommodityPowerForward,&accept, 0 },
	{ "CommoditySwap",VF_CommoditySwap,&accept, 0 },
	{ "CommodityTimeSpread",VF_CommodityTimeSpread,&accept, 0 },
	{ "CommodityTrade",VF_CommodityTrade,&accept, 0 },
	{ "CompoundingFixedLeg",VF_CompoundingFixedLeg,&accept, 0 },
	{ "ContingentCDS",VF_ContingentCDS,&accept, 0 },
	{ "ConvertibleBondAssetSwap",VF_ConvertibleBondAssetSwap,&accept, 0 },
	{ "ConvertibleBondAssetSwap2",VF_ConvertibleBondAssetSwap2,&accept, 0 },
	{ "ConvertibleBondOption",VF_ConvertibleBondOption,&accept, 0 },
	{ "CorridorCapFloor",VF_CorridorCapFloor,&accept, 0 },
	{ "CorridorChooser",VF_CorridorChooser,&accept, 0 },
	{ "CorridorCMSSpread",VF_CorridorCMSSpread,&accept, 0 },
	{ "CorridorCHT",VF_CorridorCHT,&accept, 0 },
	{ "CorridorCommodity",VF_CorridorCommodity,&accept, 0 },
	{ "CorridorCommodityFuture",VF_CorridorCommodityFuture,&accept, 0 },
	{ "CorridorCommodityNew",VF_CorridorCommodityNew,&accept, 0 },
	{ "CorridorCommodityOld",VF_CorridorCommodityOld,&accept, 0 },
	{ "CorridorCredit",VF_CorridorCredit,&accept, 0 },
	{ "CorridorCreditBasket",VF_CorridorCreditBasket,&accept, 0 },
	{ "CorridorDoubleCommodityRate",VF_CorridorDoubleCommodityRate,&accept, 0 },
	{ "CorridorDoubleEquityRate",VF_CorridorDoubleEquityRate,&accept, 0 },
	{ "CorridorDoubleSpread",VF_CorridorDoubleSpread,&accept, 0 },
	{ "CorridorEquity",VF_CorridorEquity,&accept, 0 },
	{ "CorridorFX",VF_CorridorFX,&accept, 0 },
	{ "CorridorFxChooser",VF_CorridorFxChooser,&accept, 0 },
	{ "CorridorGenericFuture",VF_CorridorGenericFuture,&accept, 0 },
	{ "CorridorQChooser",VF_CorridorQChooser,&accept, 0 },
	{ "CorridorQSpread",VF_CorridorQSpread,&accept, 0 },
	{ "CorridorQuanto",VF_CorridorQuanto,&accept, 0 },
	{ "CorridorSpread",VF_CorridorSpread,&accept, 0 },
	{ "CorridorTrade",VF_CorridorTrade,&accept, 0 },
	{ "CouponChooserPRD",VF_CouponChooserPRD,&accept, 0 },
	{ "CPRDChooser",VF_CPRDChooser,&accept, 0 },
	{ "CreditCMSLeg",VF_CreditCMSLeg,&accept, 0 },
	{ "CreditCPDO",VF_CreditCPDO,&accept, 0 },
	{ "CreditCPPI",VF_CreditCPPI,&accept, 0 },
	{ "CreditDefaultSwap",VF_CreditDefaultSwap,&accept, 0 },
	{ "CreditDefaultSwapOption",VF_CreditDefaultSwapOption,&accept, 0 },
	{ "CreditFuture",VF_CreditFuture,&accept, 0 },
	{ "CreditIndexBasisLimitOption",VF_CreditIndexBasisLimitOption,&accept, 0 },
	{ "CreditRecoveryLock",VF_CreditRecoveryLock,&accept, 0 },
	{ "CreditZeroCouponBasket",VF_CreditZeroCouponBasket,&accept, 0 },
	{ "CrossCurrencySwap",VF_CrossCurrencySwap,&accept, 0 },
	{ "CrossCurrencySwapFixed",VF_CrossCurrencySwapFixed,&accept, 0 },
	{ "CrossCurrencySwapFloating",VF_CrossCurrencySwapFloating,&accept, 0 },
	{ "CrossCurrencySwaption",VF_CrossCurrencySwaption,&accept, 0 },
	{ "CVAFromExposures",VF_CVAFromExposures,&accept, 0 },
	{ "CVAPortfolio",VF_CVAPortfolio,&accept, 0 },
	{ "CVARiskyPortfolio",VF_CVARiskyPortfolio,&accept, 0 },
	{ "DepositLoan",VF_DepositLoan,&accept, 0 },
	{ "DualCcyBondTrade",VF_DualCcyBondTrade,&accept, 0 },
	{ "EquityDividendSwap",VF_EquityDividendSwap,&accept, 0 },
	{ "EquityFuture",VF_EquityFuture,&accept, 0 },
	{ "EquityFutureOption",VF_EquityFutureOption,&accept, 0 },
	{ "EquityIndexTotalReturn",VF_EquityIndexTotalReturn,&accept, 0 },
	{ "EquityOption",VF_EquityOption,&accept, 0 },
	{ "Equity0ption2",VF_Equity0ption2,&accept, 0 },
	{ "Equity0ptionSwap",VF_Equity0ptionSwap,&accept, 0 },
	{ "EquitySwap",VF_EquitySwap,&accept, 0 },
	{ "EquityTrade",VF_EquityTrade,&accept, 0 },
	{ "EquityVarSwap",VF_EquityVarSwap,&accept, 0 },
	{ "EquivalentVanillaTrade",VF_EquivalentVanillaTrade,&accept, 0 },
	{ "ExoticBondCashFlows",VF_ExoticBondCashFlows,&accept, 0 },
	{ "ExoticBondTrade",VF_ExoticBondTrade,&accept, 0 },
	{ "ExoticHybridTrade",VF_ExoticHybridTrade,&accept, 0 },
	{ "ExoticlnterestRateTrade",VF_ExoticlnterestRateTrade,&accept, 0 },
	{ "ExtendedRiskyFixedCashFlows",VF_ExtendedRiskyFixedCashFlows,&accept, 0 },
	{ "ExternalTrade",VF_ExternalTrade,&accept, 0 },
	{ "FinanceAdjustment",VF_FinanceAdjustment,&accept, 0 },
	{ "FirstToDefaultCDS",VF_FirstToDefaultCDS,&accept, 0 },
	{ "FirstToDefaultCDSBasket",VF_FirstToDefaultCDSBasket,&accept, 0 },
	{ "FixedAssetSwap",VF_FixedAssetSwap,&accept, 0 },
	{ "FixedCashFlows",VF_FixedCashFlows,&accept, 0 },
	{ "FixedLeg",VF_FixedLeg,&accept, 0 },
	{ "FixedLegPartiallyCompounded",VF_FixedLegPartiallyCompounded,&accept, 0 },
	{ "FixedLegUntilDefault",VF_FixedLegUntilDefault,&accept, 0 },
	{ "FloatingLegUntilDefault",VF_FloatingLegUntilDefault,&accept, 0 },
	{ "FloatingLegVithRatio",VF_FloatingLegVithRatio,&accept, 0 },
	{ "FloatingSinglePaymentOnDefault",VF_FloatingSinglePaymentOnDefault,&accept, 0 },
	{ "FloatingTermDeposit",VF_FloatingTermDeposit,&accept, 0 },
	{ "ForwardBondTrade",VF_ForwardBondTrade,&accept, 0 },
	{ "ForwardRateAgreement",VF_ForwardRateAgreement,&accept, 0 },
	{ "ForwardStartSwaption",VF_ForwardStartSwaption,&accept, 0 },
	{ "FRNOption",VF_FRNOption,&accept, 0 },
	{ "FRNTrade",VF_FRNTrade,&accept, 0 },
	{ "FundingPortfolio",VF_FundingPortfolio,&accept, 0 },
	{ "FxBarrier2",VF_FxBarrier2,&accept, 0 },
	{ "FxBermudan",VF_FxBermudan,&accept, 0 },
	{ "FxBermudanQuanto",VF_FxBermudanQuanto,&accept, 0 },
	{ "FXCMSDualRateOption",VF_FXCMSDualRateOption,&accept, 0 },
	{ "FxDigital",VF_FxDigital,&accept, 0 },
	{ "FXForward",VF_FXForward,&accept, 0 },
	{ "FXForwardBasket",VF_FXForwardBasket,&accept, 0 },
	{ "FxFuture",VF_FxFuture,&accept, 0 },
	{ "FXGenericTrade",VF_FXGenericTrade,&accept, 0 },
	{ "FxMultipleOption",VF_FxMultipleOption,&accept, 0 },
	{ "FxOption",VF_FxOption,&accept, 0 },
	{ "FxOptionLeg",VF_FxOptionLeg,&accept, 0 },
	{ "FxOptionStrip",VF_FxOptionStrip,&accept, 0 },
	{ "FxSwapRolling",VF_FxSwapRolling,&accept, 0 },
	{ "FxTARN",VF_FxTARN,&accept, 0 },
	{ "FxVarianceSwap",VF_FxVarianceSwap,&accept, 0 },
	{ "GearedCallableRF",VF_GearedCallableRF,&accept, 0 },
	{ "GeneralCallableTrade",VF_GeneralCallableTrade,&accept, 0 },
	{ "GenericFuture",VF_GenericFuture,&accept, 0 },
	{ "GenericFutureOption",VF_GenericFutureOption,&accept, 0 },
	{ "HighGradeDCBTrade",VF_HighGradeDCBTrade,&accept, 0 },
	{ "HighYieldBondOption",VF_HighYieldBondOption,&accept, 0 },
	{ "HighYieldBondTrade",VF_HighYieldBondTrade,&accept, 0 },
	{ "HighYieldDCBTrade",VF_HighYieldDCBTrade,&accept, 0 },
	{ "InflationAssetSwap",VF_InflationAssetSwap,&accept, 0 },
	{ "InflationCapFloor",VF_InflationCapFloor,&accept, 0 },
	{ "InflationCapFloorZeroCoupon",VF_InflationCapFloorZeroCoupon,&accept, 0 },
	{ "InflationCashFlows",VF_InflationCashFlows,&accept, 0 },
	{ "InflationCMSSpread",VF_InflationCMSSpread,&accept, 0 },
	{ "InflationCrossCurrencySwap",VF_InflationCrossCurrencySwap,&accept, 0 },
	{ "InflationExoticBondAssetSwap",VF_InflationExoticBondAssetSwap,&accept, 0 },
	{ "InflationIndexFloatingSwap",VF_InflationIndexFloatingSwap,&accept, 0 },
	{ "InflationlndexForward",VF_InflationlndexForward,&accept, 0 },
	{ "InflationlndexFuture",VF_InflationlndexFuture,&accept, 0 },
	{ "InflationLeg",VF_InflationLeg,&accept, 0 },
	{ "InflationLPlFlows",VF_InflationLPlFlows,&accept, 0 },
	{ "InflationLPISwap",VF_InflationLPISwap,&accept, 0 },
	{ "InflationPaymentOnDefault",VF_InflationPaymentOnDefault,&accept, 0 },
	{ "InflationQuantoCapFloor",VF_InflationQuantoCapFloor,&accept, 0 },
	{ "InflationQuantoLeg",VF_InflationQuantoLeg,&accept, 0 },
	{ "InflationSpreadOptionTrade",VF_InflationSpreadOptionTrade,&accept, 0 },
	{ "InflationSwapleroCoupon",VF_InflationSwapleroCoupon,&accept, 0 },
	{ "InterestOnlnterest",VF_InterestOnlnterest,&accept, 0 },
	{ "InterestRateBundleFuture",VF_InterestRateBundleFuture,&accept, 0 },
	{ "InterestRateBundleFutureOption",VF_InterestRateBundleFutureOption,&accept, 0 },
	{ "InterestRateFuture",VF_InterestRateFuture,&accept, 0 },
	{ "InterestRateFutureOption",VF_InterestRateFutureOption,&accept, 0 },
	{ "InterestRateFutureOptionOTC",VF_InterestRateFutureOptionOTC,&accept, 0 },
	{ "InterestRateSwap",VF_InterestRateSwap,&accept, 0 },
	{ "InterestRateSwapCashSettle",VF_InterestRateSwapCashSettle,&accept, 0 },
	{ "InterestRateSwapFuture",VF_InterestRateSwapFuture,&accept, 0 },
	{ "IrregularMultiCurrencySwaption",VF_IrregularMultiCurrencySwaption,&accept, 0 },
	{ "IrregularSwaption",VF_IrregularSwaption,&accept, 0 },
	{ "LeveragedCDSBasketTranche",VF_LeveragedCDSBasketTranche,&accept, 0 },
	{ "LeveragedCDSGap",VF_LeveragedCDSGap,&accept, 0 },
	{ "LeveragedSinglePaymentOnDefault",VF_LeveragedSinglePaymentOnDefault,&accept, 0 },
	{ "LMMExoticSwap",VF_LMMExoticSwap,&accept, 0 },
	{ "ManagedPortfolio",VF_ManagedPortfolio,&accept, 0 },
	{ "MidCurveFutureOption",VF_MidCurveFutureOption,&accept, 0 },
	{ "MortgageOption",VF_MortgageOption,&accept, 0 },
	{ "MortgageTBATrade",VF_MortgageTBATrade,&accept, 0 },
	{ "NonDeliverableFXForward",VF_NonDeliverableFXForward,&accept, 0 },
	{ "NonDeliverableFxLeg",VF_NonDeliverableFxLeg,&accept, 0 },
	{ "NonDeliverableTrade",VF_NonDeliverableTrade,&accept, 0 },
	{ "NonLiborlRFuture",VF_NonLiborlRFuture,&accept, 0 },
	{ "NonLiborlRFutureOption",VF_NonLiborlRFutureOption,&accept, 0 },
	{ "NonStandardIndexSwaption",VF_NonStandardIndexSwaption,&accept, 0 },
	{ "OnshorelRFuture",VF_OnshorelRFuture,&accept, 0 },
	{ "PeriodicCapFloor",VF_PeriodicCapFloor,&accept, 0 },
	{ "PortfolioCashFlows",VF_PortfolioCashFlows,&accept, 0 },
	{ "PRD",VF_PRD,&accept, 0 },
	{ "ProjectFinanceTrade",VF_ProjectFinanceTrade,&accept, 0 },
	{ "QCMSCapFloor",VF_QCMSCapFloor,&accept, 0 },
	{ "QCMSFxDigitalLeg",VF_QCMSFxDigitalLeg,&accept, 0 },
	{ "QCMSFxLeg",VF_QCMSFxLeg,&accept, 0 },
	{ "QCMSLeg",VF_QCMSLeg,&accept, 0 },
	{ "QuantoCDS",VF_QuantoCDS,&accept, 0 },
	{ "QuantoFxForward",VF_QuantoFxForward,&accept, 0 },
	{ "QuantoFxOption",VF_QuantoFxOption,&accept, 0 },
	{ "RateDigital",VF_RateDigital,&accept, 0 },
	{ "RateDigitalLeg",VF_RateDigitalLeg,&accept, 0 },
	{ "RateDigitalQCMSLeg",VF_RateDigitalQCMSLeg,&accept, 0 },
	{ "ReflexTrade",VF_ReflexTrade,&accept, 0 },
	{ "RegularReflexTrade",VF_RegularReflexTrade,&accept, 0 },
	{ "ResettableCapFloor",VF_ResettableCapFloor,&accept, 0 },
	{ "RiskyAssetSwap",VF_RiskyAssetSwap,&accept, 0 },
	{ "RiskyBermudanSwaption",VF_RiskyBermudanSwaption,&accept, 0 },
	{ "RiskyCrossCurrencySwap",VF_RiskyCrossCurrencySwap,&accept, 0 },
	{ "RiskyFixedCashFlows",VF_RiskyFixedCashFlows,&accept, 0 },
	{ "RiskyFRNTrade",VF_RiskyFRNTrade,&accept, 0 },
	{ "RiskyInterestRateTrade",VF_RiskyInterestRateTrade,&accept, 0 },
	{ "RollingGuaranteeLeg",VF_RollingGuaranteeLeg,&accept, 0 },
	{ "SemiAsianResettable",VF_SemiAsianResettable,&accept, 0 },
	{ "SinglePaymentOnDefault",VF_SinglePaymentOnDefault,&accept, 0 },
	{ "Snowball",VF_Snowball,&accept, 0 },
	{ "SpreadOptionEquityTrade",VF_SpreadOptionEquityTrade,&accept, 0 },
	{ "SpreadOptionTrade",VF_SpreadOptionTrade,&accept, 0 },
	{ "StructuredLoan",VF_StructuredLoan,&accept, 0 },
	{ "SwapFloatingLeg",VF_SwapFloatingLeg,&accept, 0 },
	{ "SwapFloatingLegMtM",VF_SwapFloatingLegMtM,&accept, 0 },
	{ "SwapFloatingLegXCcyRate",VF_SwapFloatingLegXCcyRate,&accept, 0 },
	{ "Swaption",VF_Swaption,&accept, 0 },
	{ "SwaptionOnDefault",VF_SwaptionOnDefault,&accept, 0 },
	{ "SwaptionOnDefaultCrossCurrency",VF_SwaptionOnDefaultCrossCurrency,&accept, 0 },
	{ "SwaptionOnDefaultCrossCurrencyFixed",VF_SwaptionOnDefaultCrossCurrencyFixed,&accept, 0 },
	{ "SwaptionOnDefaultCrossCurrencyFloating",VF_SwaptionOnDefaultCrossCurrencyFloating,&accept, 0 },
	{ "SyntheticBondFutureOptionTrade",VF_SyntheticBondFutureOptionTrade,&accept, 0 },
	{ "SyntheticBondFutureTrade",VF_SyntheticBondFutureTrade,&accept, 0 },
	{ "SyntheticlnterestRateFuture",VF_SyntheticlnterestRateFuture,&accept, 0 },
	{ "SyntheticlnterestRateFutureOption",VF_SyntheticlnterestRateFutureOption,&accept, 0 },
	{ "SyntheticOnshorelRFuture",VF_SyntheticOnshorelRFuture,&accept, 0 },
	{ "TargetPRD",VF_TargetPRD,&accept, 0 },
	{ "TargetSpreadOption",VF_TargetSpreadOption,&accept, 0 },
	{ "TotalReturnSwapCustomCSA",VF_TotalReturnSwapCustomCSA,&accept, 0 },
	{ "TotalReturnSwapIndex",VF_TotalReturnSwapIndex,&accept, 0 },
	{ "TotalReturnSwapLeg",VF_TotalReturnSwapLeg,&accept, 0 },
	{ "TriggerCorridor",VF_TriggerCorridor,&accept, 0 },
	{ "TriggerEquityLiborOption",VF_TriggerEquityLiborOption,&accept, 0 },
	{ "TriggerEquityRatchet",VF_TriggerEquityRatchet,&accept, 0 },
	{ "TriggerReverseFloater",VF_TriggerReverseFloater,&accept, 0 },
	{ "TriggerSnowball",VF_TriggerSnowball,&accept, 0 },
	{ "VolatilityBond",VF_VolatilityBond,&accept, 0 },
	{ "ZCBondCollateralTrade",VF_ZCBondCollateralTrade,&accept, 0 }
};



typedef enum
{
	VF_UNKNOWN = 0,
	VF_ABSCDSBasketTranche,
	VF_ABSCreditDefaultSwap,
	VF_AlgorithmiclndexBasketTotalReturn,
	VF_AlgorithmicIndexBasketTotalReturn2,
	VF_AlgorithmicIndexBasketTotalReturnOption,
	VF_AlgorithmicIndexLiborOption,
	VF_AlgorithmicIndexTotalReturn,
	VF_AlgorithmicIndexTotalReturnOption,
	VF_AnnuityOption3,
	VF_AsianDigitalQCMSLeg,
	VF_AsianSpreadOption,
	VF_AutoCap,
	VF_BarrierPRD,
	VF_BarrierPRD2,
	VF_BarrierSwap,
	VF_BasisSwap,
	VF_BasisSwapLegUntilDefault,
	VF_BasisSwapMtM,
	VF_BasisSwapMtM2,
	VF_BasisSwaption,
	VF_BermudanAsianSpreadOption,
	VF_BermudanCDOCorridor,
	VF_BermudanCorridor,
	VF_BermudanDoubleEquityCorridor,
	VF_BermudanDoubleSpreadCorridor,
	VF_BermudanQuantoCorridor,
	VF_BermudanSpreadCorridor,
	VF_BermudanSwaption,
	VF_BermudanSwaption2,
	VF_BermudanSwaption2BondLinked,
	VF_BermudanZeroSwaption,
	VF_BestOflnflationAndEquity,
	VF_BondASMOption,
	VF_BondCashFlowsTrade,
	VF_BondExchangeableASMOption,
	VF_BondFixedASMOption,
	VF_BondFutureOptionTrade,
	VF_BondFutureTrade,
	VF_BondGapOption,
	VF_BondOption,
	VF_BondOptionTrade,
	VF_BondRepo,
	VF_BondRepoCustom,
	VF_BondTrade,
	VF_BradyBondTrade,
	VF_BradyFRNTrade,
	VF_CallableBondAssetSwap,
	VF_CallableCDOCorridor,
	VF_CallableCorridor,
	VF_CallableCorridorBondLinked,
	VF_CallableCreditDefaultSwap,
	VF_CallableDoubleSpreadCorridor,
	VF_CallableDualReverseFloater,
	VF_CallableDualSpread,
	VF_CallableEquityOption,
	VF_CallableFxIRSpreadOption,
	VF_CallableFxTrade,
	VF_CallableLiborTrade,
	VF_CallablePRD,
	VF_CallableQuantoCorridor,
	VF_CallableRatchetCorridor,
	VF_CallableRepoTrade,
	VF_CallableReverseFloater,
	VF_CallableRiskyAssetSwap,
	VF_CallableRiskyFloatingAssetSwap,
	VF_CallableRiskySpreadOption,
	VF_CallableSpreadCorridor,
	VF_CallableSpreadOption,
	VF_CapFloor,
	VF_CashBalance,
	VF_CashlndexOption,
	VF_CD0Forward,
	VF_CDOofCDOs,
	VF_CDSBasketIndex,
	VF_CDSBasketIndexCapFloor,
	VF_CDSBasketIndexCMSLeg,
	VF_CDSBasketIndexOption,
	VF_CDSBasketRollingIndexCapFloor,
	VF_CDSBasketRollingIndexCMSLeg,
	VF_CDSBasketTranche,
	VF_CDSBasketTranchProtectionTrade,
	VF_CDSPortfolio,
	VF_ChooserTarn,
	VF_CMMForwardRateAgreement,
	VF_CMMLeg,
	VF_CMSDualRateOption,
	VF_CMSLinkedIRRSwap,
	VF_CMSMultiplier,
	VF_CMSSpreadHedged,
	VF_CMSTripleRateOption,
	VF_CMTCapFloor,
	VF_CMTLeg,
	VF_CMTLeg2,
	VF_CommodityAPO,
	VF_CommodityBasisSwap,
	VF_CommodityBasketOption,
	VF_CommodityBasketSwap,
	VF_CommodityClearedAPO,
	VF_CommodityClearedBasisSwap,
	VF_CommodityClearedGasForward,
	VF_CommodityClearedPowerForward,
	VF_CommodityClearedSwap,
	VF_CommodityCompoAPO,
	VF_CommodityCompoSwap,
	VF_CommodityDerivedInstrumentPrice,
	VF_CommodityEnergyOption,
	VF_CommodityFloatingForward,
	VF_CommodityFuture,
	VF_CommodityFutureOption,
	VF_CommodityFutureOptionTrade,
	VF_CommodityFutureTrade,
	VF_CommodityGasForward,
	VF_CommodityGasStorage,
	VF_Commodity0ption,
	VF_Commodity0ptionTrade,
	VF_CommodityPowerForward,
	VF_CommoditySwap,
	VF_CommodityTimeSpread,
	VF_CommodityTrade,
	VF_CompoundingFixedLeg,
	VF_ContingentCDS,
	VF_ConvertibleBondAssetSwap,
	VF_ConvertibleBondAssetSwap2,
	VF_ConvertibleBondOption,
	VF_CorridorCapFloor,
	VF_CorridorChooser,
	VF_CorridorCMSSpread,
	VF_CorridorCHT,
	VF_CorridorCommodity,
	VF_CorridorCommodityFuture,
	VF_CorridorCommodityNew,
	VF_CorridorCommodityOld,
	VF_CorridorCredit,
	VF_CorridorCreditBasket,
	VF_CorridorDoubleCommodityRate,
	VF_CorridorDoubleEquityRate,
	VF_CorridorDoubleSpread,
	VF_CorridorEquity,
	VF_CorridorFX,
	VF_CorridorFxChooser,
	VF_CorridorGenericFuture,
	VF_CorridorQChooser,
	VF_CorridorQSpread,
	VF_CorridorQuanto,
	VF_CorridorSpread,
	VF_CorridorTrade,
	VF_CouponChooserPRD,
	VF_CPRDChooser,
	VF_CreditCMSLeg,
	VF_CreditCPDO,
	VF_CreditCPPI,
	VF_CreditDefaultSwap,
	VF_CreditDefaultSwapOption,
	VF_CreditFuture,
	VF_CreditIndexBasisLimitOption,
	VF_CreditRecoveryLock,
	VF_CreditZeroCouponBasket,
	VF_CrossCurrencySwap,
	VF_CrossCurrencySwapFixed,
	VF_CrossCurrencySwapFloating,
	VF_CrossCurrencySwaption,
	VF_CVAFromExposures,
	VF_CVAPortfolio,
	VF_CVARiskyPortfolio,
	VF_DepositLoan,
	VF_DualCcyBondTrade,
	VF_EquityDividendSwap,
	VF_EquityFuture,
	VF_EquityFutureOption,
	VF_EquityIndexTotalReturn,
	VF_EquityOption,
	VF_Equity0ption2,
	VF_Equity0ptionSwap,
	VF_EquitySwap,
	VF_EquityTrade,
	VF_EquityVarSwap,
	VF_EquivalentVanillaTrade,
	VF_ExoticBondCashFlows,
	VF_ExoticBondTrade,
	VF_ExoticHybridTrade,
	VF_ExoticlnterestRateTrade,
	VF_ExtendedRiskyFixedCashFlows,
	VF_ExternalTrade,
	VF_FinanceAdjustment,
	VF_FirstToDefaultCDS,
	VF_FirstToDefaultCDSBasket,
	VF_FixedAssetSwap,
	VF_FixedCashFlows,
	VF_FixedLeg,
	VF_FixedLegPartiallyCompounded,
	VF_FixedLegUntilDefault,
	VF_FloatingLegUntilDefault,
	VF_FloatingLegVithRatio,
	VF_FloatingSinglePaymentOnDefault,
	VF_FloatingTermDeposit,
	VF_ForwardBondTrade,
	VF_ForwardRateAgreement,
	VF_ForwardStartSwaption,
	VF_FRNOption,
	VF_FRNTrade,
	VF_FundingPortfolio,
	VF_FxBarrier2,
	VF_FxBermudan,
	VF_FxBermudanQuanto,
	VF_FXCMSDualRateOption,
	VF_FxDigital,
	VF_FXForward,
	VF_FXForwardBasket,
	VF_FxFuture,
	VF_FXGenericTrade,
	VF_FxMultipleOption,
	VF_FxOption,
	VF_FxOptionLeg,
	VF_FxOptionStrip,
	VF_FxSwapRolling,
	VF_FxTARN,
	VF_FxVarianceSwap,
	VF_GearedCallableRF,
	VF_GeneralCallableTrade,
	VF_GenericFuture,
	VF_GenericFutureOption,
	VF_HighGradeDCBTrade,
	VF_HighYieldBondOption,
	VF_HighYieldBondTrade,
	VF_HighYieldDCBTrade,
	VF_InflationAssetSwap,
	VF_InflationCapFloor,
	VF_InflationCapFloorZeroCoupon,
	VF_InflationCashFlows,
	VF_InflationCMSSpread,
	VF_InflationCrossCurrencySwap,
	VF_InflationExoticBondAssetSwap,
	VF_InflationIndexFloatingSwap,
	VF_InflationlndexForward,
	VF_InflationlndexFuture,
	VF_InflationLeg,
	VF_InflationLPlFlows,
	VF_InflationLPISwap,
	VF_InflationPaymentOnDefault,
	VF_InflationQuantoCapFloor,
	VF_InflationQuantoLeg,
	VF_InflationSpreadOptionTrade,
	VF_InflationSwapleroCoupon,
	VF_InterestOnlnterest,
	VF_InterestRateBundleFuture,
	VF_InterestRateBundleFutureOption,
	VF_InterestRateFuture,
	VF_InterestRateFutureOption,
	VF_InterestRateFutureOptionOTC,
	VF_InterestRateSwap,
	VF_InterestRateSwapCashSettle,
	VF_InterestRateSwapFuture,
	VF_IrregularMultiCurrencySwaption,
	VF_IrregularSwaption,
	VF_LeveragedCDSBasketTranche,
	VF_LeveragedCDSGap,
	VF_LeveragedSinglePaymentOnDefault,
	VF_LMMExoticSwap,
	VF_ManagedPortfolio,
	VF_MidCurveFutureOption,
	VF_MortgageOption,
	VF_MortgageTBATrade,
	VF_NonDeliverableFXForward,
	VF_NonDeliverableFxLeg,
	VF_NonDeliverableTrade,
	VF_NonLiborlRFuture,
	VF_NonLiborlRFutureOption,
	VF_NonStandardIndexSwaption,
	VF_OnshorelRFuture,
	VF_PeriodicCapFloor,
	VF_PortfolioCashFlows,
	VF_PRD,
	VF_ProjectFinanceTrade,
	VF_QCMSCapFloor,
	VF_QCMSFxDigitalLeg,
	VF_QCMSFxLeg,
	VF_QCMSLeg,
	VF_QuantoCDS,
	VF_QuantoFxForward,
	VF_QuantoFxOption,
	VF_RateDigital,
	VF_RateDigitalLeg,
	VF_RateDigitalQCMSLeg,
	VF_ReflexTrade,
	VF_RegularReflexTrade,
	VF_ResettableCapFloor,
	VF_RiskyAssetSwap,
	VF_RiskyBermudanSwaption,
	VF_RiskyCrossCurrencySwap,
	VF_RiskyFixedCashFlows,
	VF_RiskyFRNTrade,
	VF_RiskyInterestRateTrade,
	VF_RollingGuaranteeLeg,
	VF_SemiAsianResettable,
	VF_SinglePaymentOnDefault,
	VF_Snowball,
	VF_SpreadOptionEquityTrade,
	VF_SpreadOptionTrade,
	VF_StructuredLoan,
	VF_SwapFloatingLeg,
	VF_SwapFloatingLegMtM,
	VF_SwapFloatingLegXCcyRate,
	VF_Swaption,
	VF_SwaptionOnDefault,
	VF_SwaptionOnDefaultCrossCurrency,
	VF_SwaptionOnDefaultCrossCurrencyFixed,
	VF_SwaptionOnDefaultCrossCurrencyFloating,
	VF_SyntheticBondFutureOptionTrade,
	VF_SyntheticBondFutureTrade,
	VF_SyntheticlnterestRateFuture,
	VF_SyntheticlnterestRateFutureOption,
	VF_SyntheticOnshorelRFuture,
	VF_TargetPRD,
	VF_TargetSpreadOption,
	VF_TotalReturnSwapCustomCSA,
	VF_TotalReturnSwapIndex,
	VF_TotalReturnSwapLeg,
	VF_TriggerCorridor,
	VF_TriggerEquityLiborOption,
	VF_TriggerEquityRatchet,
	VF_TriggerReverseFloater,
	VF_TriggerSnowball,
	VF_VolatilityBond,
	VF_ZCBondCollateralTrade
} VFNAME;
